#!/usr/bin/env python3
"""Tax report generator — builds monthly/quarterly/annual spend reports from receipts.jsonl.

Usage:
    python3 tax_report.py                    # Current year summary (CSV + Markdown)
    python3 tax_report.py --year 2025        # Specific year
    python3 tax_report.py --quarter 2026-Q1  # Specific quarter
    python3 tax_report.py --month 2026-04    # Specific month
    python3 tax_report.py --format csv       # CSV only
    python3 tax_report.py --format md        # Markdown only
"""
import argparse
import csv
import io
from datetime import datetime
from pathlib import Path

import receipts

REPORTS_DIR = Path(__file__).parent / "reports"


def date_range_for_year(year: int) -> tuple[str, str]:
    return f"{year}-01-01", f"{year}-12-31"


def date_range_for_quarter(quarter: str) -> tuple[str, str]:
    """Parse '2026-Q1' → ('2026-01-01', '2026-03-31')."""
    year, q = quarter.split("-Q")
    year = int(year)
    q = int(q)
    starts = {1: "01-01", 2: "04-01", 3: "07-01", 4: "10-01"}
    ends = {1: "03-31", 2: "06-30", 3: "09-30", 4: "12-31"}
    return f"{year}-{starts[q]}", f"{year}-{ends[q]}"


def date_range_for_month(month: str) -> tuple[str, str]:
    """Parse '2026-04' → ('2026-04-01', '2026-04-30' or 31)."""
    year, m = month.split("-")
    year, m = int(year), int(m)
    from calendar import monthrange
    last = monthrange(year, m)[1]
    return f"{year}-{m:02d}-01", f"{year}-{m:02d}-{last:02d}"


def render_csv(rows: list[dict]) -> str:
    out = io.StringIO()
    fields = ["date", "vendor", "category", "amount", "currency", "description", "email_subject"]
    w = csv.DictWriter(out, fieldnames=fields, extrasaction="ignore")
    w.writeheader()
    for r in rows:
        w.writerow(r)
    return out.getvalue()


def render_markdown(rows: list[dict], period_label: str) -> str:
    summary = receipts.summarize(rows)

    lines = [
        f"# AI & Business Software Tax Report",
        f"",
        f"**Period:** {period_label}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
        f"## Summary",
        f"",
        f"- **Total receipts:** {summary['count']}",
        f"- **Total spend:** ${summary['total']:,.2f}",
        f"",
        f"## By Category",
        f"",
        f"| Category | Amount | % of Total |",
        f"|----------|-------:|-----------:|",
    ]
    total = summary["total"] or 1
    for cat, amt in summary["by_category"].items():
        pct = amt / total * 100
        lines.append(f"| {cat} | ${amt:,.2f} | {pct:.1f}% |")

    lines += [
        f"",
        f"## By Vendor",
        f"",
        f"| Vendor | Receipts | Total |",
        f"|--------|---------:|------:|",
    ]
    # Count per vendor
    vend_counts: dict[str, int] = {}
    for r in rows:
        v = r.get("vendor") or "unknown"
        vend_counts[v] = vend_counts.get(v, 0) + 1
    for vend, amt in summary["by_vendor"].items():
        lines.append(f"| {vend} | {vend_counts.get(vend, 0)} | ${amt:,.2f} |")

    lines += [
        f"",
        f"## All Receipts",
        f"",
        f"| Date | Vendor | Category | Amount | Description |",
        f"|------|--------|----------|-------:|-------------|",
    ]
    for r in rows:
        desc = (r.get("description") or r.get("email_subject") or "").replace("|", "\\|")[:60]
        lines.append(
            f"| {r.get('date','')} | {r.get('vendor','')} | {r.get('category','')} | "
            f"${float(r.get('amount') or 0):,.2f} | {desc} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"_Generated by token-tracker tax_report.py. PDF receipts archived under `receipts/YYYY/MM/`._",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate tax report from receipts.jsonl")
    parser.add_argument("--year", type=int, help="Report a full calendar year")
    parser.add_argument("--quarter", help="Report a quarter, e.g. 2026-Q1")
    parser.add_argument("--month", help="Report a month, e.g. 2026-04")
    parser.add_argument("--format", choices=["csv", "md", "both"], default="both")
    parser.add_argument("--output-dir", type=Path, default=REPORTS_DIR)
    args = parser.parse_args()

    if args.year:
        start, end = date_range_for_year(args.year)
        label = f"Year {args.year}"
        slug = f"{args.year}-annual"
    elif args.quarter:
        start, end = date_range_for_quarter(args.quarter)
        label = args.quarter
        slug = args.quarter.replace("-", "-")
    elif args.month:
        start, end = date_range_for_month(args.month)
        label = args.month
        slug = args.month.replace("-", "-")
    else:
        year = datetime.now().year
        start, end = date_range_for_year(year)
        label = f"Year {year} (YTD)"
        slug = f"{year}-ytd"

    rows = receipts.query(start_date=start, end_date=end)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    if args.format in ("csv", "both"):
        csv_path = args.output_dir / f"tax-report-{slug}.csv"
        csv_path.write_text(render_csv(rows))
        print(f"CSV:      {csv_path}")

    if args.format in ("md", "both"):
        md_path = args.output_dir / f"tax-report-{slug}.md"
        md_path.write_text(render_markdown(rows, label))
        print(f"Markdown: {md_path}")

    # Print summary to stdout
    summary = receipts.summarize(rows)
    print(f"\n{label}: {summary['count']} receipts, ${summary['total']:,.2f} total")


if __name__ == "__main__":
    main()
