#!/usr/bin/env python3
"""Auto-fix: extract key exports from a file and append to project's CLAUDE.md."""
import re
import sys
from pathlib import Path


def extract_symbols(content: str, file_ext: str):
    """Extract top-level functions, classes, exports from source code."""
    symbols = []

    if file_ext in (".ts", ".tsx", ".js", ".jsx"):
        patterns = [
            r"export\s+(?:default\s+)?(?:async\s+)?function\s+(\w+)",
            r"export\s+(?:default\s+)?class\s+(\w+)",
            r"export\s+(?:const|let|var)\s+(\w+)",
            r"^\s*(?:async\s+)?function\s+(\w+)",
            r"^\s*class\s+(\w+)",
        ]
    elif file_ext == ".py":
        patterns = [
            r"^def\s+(\w+)",
            r"^class\s+(\w+)",
            r"^async\s+def\s+(\w+)",
        ]
    else:
        patterns = [
            r"function\s+(\w+)",
            r"class\s+(\w+)",
            r"def\s+(\w+)",
        ]

    for pattern in patterns:
        for match in re.finditer(pattern, content, re.MULTILINE):
            name = match.group(1)
            if name and not name.startswith("_") and name not in symbols:
                symbols.append(name)

    return symbols[:20]


def find_project_root(start: Path) -> Path:
    """Walk up from a file path to find project root."""
    cur = start.parent if start.is_file() else start
    for _ in range(10):
        for marker in (".git", "package.json", "pyproject.toml", "go.mod", "Cargo.toml"):
            if (cur / marker).exists():
                return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    return start.parent if start.is_file() else start


def run(file_path, project_root=None) -> Path:
    """Append a Quick Reference section for file_path to project's CLAUDE.md."""
    file_path = Path(file_path).resolve()
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    project_root = Path(project_root).resolve() if project_root else find_project_root(file_path)
    try:
        rel_path = file_path.relative_to(project_root)
    except ValueError:
        rel_path = file_path.name

    content = file_path.read_text(errors="replace")
    symbols = extract_symbols(content, file_path.suffix.lower())

    section_header = f"## Quick Reference: {rel_path}"
    section_body = "\n".join(f"- `{s}`" for s in symbols) if symbols else "- (no public symbols extracted)"
    new_section = f"\n\n{section_header}\n\n_Auto-generated by token-tracker to prevent re-reads._\n\n{section_body}\n"

    claude_md = project_root / "CLAUDE.md"
    if claude_md.exists():
        existing = claude_md.read_text()
        if section_header in existing:
            return claude_md
        claude_md.write_text(existing.rstrip() + new_section)
    else:
        claude_md.write_text(f"# {project_root.name}\n{new_section}")

    return claude_md


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 add_to_claude_md.py <file_path>", file=sys.stderr)
        sys.exit(1)
    out = run(Path(sys.argv[1]))
    print(f"Updated: {out}")
